### ISSUE TITLE
debugging is broken with Java 8u60

### ISSUE THREAD

**Issue by apmckinlay** [apmckinlay/jsuneido#2]
Throwing an exception from the WorkSpace
Works with 8u51 (get Suneido debugger)
With 8u60 jSuneido exits and this is in error.log

`2015-09-03 13:16:06 FATAL: REPL FAILED: suneido.SuInternalError: it should not be possible to instantiate CallstackAll without initializing stackInfo
suneido.SuInternalError: it should not be possible to instantiate CallstackAll without initializing stackInfo
    at suneido.debug.CallstackAll.checkStackInfo(CallstackAll.java:95)
    at suneido.debug.CallstackAll.makeFrames(CallstackAll.java:252)
    at suneido.debug.Callstack.frames(Callstack.java:73)
    at suneido.debug.Callstack.size(Callstack.java:86)
    at suneido.runtime.Except.Callstack(Except.java:123)
    at suneido.runtime.Builtin$Method0.eval0(Builtin.java:78)
    at suneido.runtime.Ops.invoke0(Ops.java:606)
    at suneido.code.MessageLoopErrorLog.call2(library[stdlib]->MessageLoopErrorLog:10)
    at suneido.runtime.SuCallable.invoke2(SuCallable.java:138)
    at suneido.code.AppMessageLoopException.call3(library[stdlib]->AppMessageLoopException:13)
    at suneido.runtime.SuCallable.invoke3(SuCallable.java:142)
    at suneido.code.AppMessageLoop.call1(library[stdlib]->AppMessageLoop:29)
    at suneido.runtime.SuCallBase1.call0(SuCallBase1.java:25)
    at suneido.runtime.SuCallable.invoke0(SuCallable.java:130)
    at suneido.code.Init£startup.eval0(library[stdlib]->Init:24)
    at suneido.runtime.Ops.invoke0(Ops.java:606)
    at suneido.code.Init£CallClass.eval0(library[stdlib]->Init:12)
    at suneido.runtime.SuClass.call0(SuClass.java:128)
    at suneido.runtime.SuCallable.invoke0(SuCallable.java:130)
    at suneido.code.eval.call0(<eval>:1)
    at suneido.runtime.Ops.call0(Ops.java:561)
    at suneido.compiler.Compiler.eval(Compiler.java:88)
    at suneido.Repl.repl2(Repl.java:36)
    at suneido.Repl.repl(Repl.java:30)
    at suneido.Suneido.doAction(Suneido.java:70)
    at suneido.Suneido.main(Suneido.java:60)`

Note: Also with 8u60, -Xcheck:jni gives a lot of warnings.
see: https://community.oracle.com/thread/3783234

@vcschapp - any ideas?

**Comment by apmckinlay** [comment]
Debug support has been removed.
